version: "3.4"
services:
  vite_docker:
   build:
    context: .
    dockerfile: Dockerfile
   container_name: react-elastic
   ports:
     - 4000:4000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   command: sh -c "npm i && npm run dev"
   tty: true